# This is to reproduce original results reported by the
# faster-rcnn paper.
# Final mAP ~ 73.08%
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: VGG16.add_VGG16_conv5_body
  NUM_CLASSES: 21
  FASTER_RCNN: True
NUM_GPUS: 2  # mimic iter_size=2
SOLVER:
  WEIGHT_DECAY: 0.0005
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001  
  GAMMA: 0.1
  # 1x schedule (note TRAIN.IMS_PER_BATCH: 1)
  MAX_ITER: 35000
  STEPS: [0, 25000]
  WARM_UP_ITERS: 0
RPN:
  SIZES: (128, 256, 512)
FAST_RCNN:
  ROI_BOX_HEAD: VGG16.add_VGG16_roi_fc_head
  ROI_XFORM_METHOD: RoIPoolF
TRAIN:
  BG_THRESH_HI: 0.5
  BG_THRESH_LO: 0.0  
  WEIGHTS: ~/.detectron_models/VGG16.pkl
  DATASETS: ('voc_2007_trainval','voc_2012_trainval')
  SCALES: (400, 500, 600, 700)
  MAX_SIZE: 1000
  IMS_PER_BATCH: 1
  BATCH_SIZE_PER_IM: 128
  RPN_MIN_SIZE: 16
TEST:
  DATASETS: ('voc_2007_test',)
  SCALE: 600
  MAX_SIZE: 1000
  NMS: 0.3
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 300
  RPN_MIN_SIZE: 16
OUTPUT_DIR: .
